name: PR Labels

on:
  pull_request_target:
    types: [opened]
    
jobs:
  mark_as_community:
    runs-on: ubuntu-latest
    steps:
      - name: Mark as Community if PR is from a fork
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['Community']
            })
